# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

oracsprt <- function(realmu, muzero, meansamp, n) {
    .Call(`_SAVA_oracsprt`, realmu, muzero, meansamp, n)
}

falphaplus <- function(alpha, sampvec, bound, t, q) {
    .Call(`_SAVA_falphaplus`, alpha, sampvec, bound, t, q)
}

falphaminus <- function(alpha, sampvec, bound, t, q) {
    .Call(`_SAVA_falphaminus`, alpha, sampvec, bound, t, q)
}

threldpp <- function(q, W, index, rej) {
    .Call(`_SAVA_threldpp`, q, W, index, rej)
}

thresaff <- function(q, w0, index, rejvec, cvec, lamb) {
    .Call(`_SAVA_thresaff`, q, w0, index, rejvec, cvec, lamb)
}

threaddis <- function(q, w0, index, rejvec, cvec, sindex, kstar, lamb, tau) {
    .Call(`_SAVA_threaddis`, q, w0, index, rejvec, cvec, sindex, kstar, lamb, tau)
}

