// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// oracsprt
double oracsprt(double realmu, double muzero, double meansamp, double n);
RcppExport SEXP _SAVA_oracsprt(SEXP realmuSEXP, SEXP muzeroSEXP, SEXP meansampSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type realmu(realmuSEXP);
    Rcpp::traits::input_parameter< double >::type muzero(muzeroSEXP);
    Rcpp::traits::input_parameter< double >::type meansamp(meansampSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(oracsprt(realmu, muzero, meansamp, n));
    return rcpp_result_gen;
END_RCPP
}
// falphaplus
double falphaplus(double alpha, NumericVector sampvec, double bound, double t, double q);
RcppExport SEXP _SAVA_falphaplus(SEXP alphaSEXP, SEXP sampvecSEXP, SEXP boundSEXP, SEXP tSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampvec(sampvecSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(falphaplus(alpha, sampvec, bound, t, q));
    return rcpp_result_gen;
END_RCPP
}
// falphaminus
double falphaminus(double alpha, NumericVector sampvec, double bound, double t, double q);
RcppExport SEXP _SAVA_falphaminus(SEXP alphaSEXP, SEXP sampvecSEXP, SEXP boundSEXP, SEXP tSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampvec(sampvecSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(falphaminus(alpha, sampvec, bound, t, q));
    return rcpp_result_gen;
END_RCPP
}
// threldpp
double threldpp(double q, double W, double index, NumericVector rej);
RcppExport SEXP _SAVA_threldpp(SEXP qSEXP, SEXP WSEXP, SEXP indexSEXP, SEXP rejSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type index(indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rej(rejSEXP);
    rcpp_result_gen = Rcpp::wrap(threldpp(q, W, index, rej));
    return rcpp_result_gen;
END_RCPP
}
// thresaff
double thresaff(double q, double w0, double index, NumericVector rejvec, NumericVector cvec, double lamb);
RcppExport SEXP _SAVA_thresaff(SEXP qSEXP, SEXP w0SEXP, SEXP indexSEXP, SEXP rejvecSEXP, SEXP cvecSEXP, SEXP lambSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< double >::type index(indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rejvec(rejvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cvec(cvecSEXP);
    Rcpp::traits::input_parameter< double >::type lamb(lambSEXP);
    rcpp_result_gen = Rcpp::wrap(thresaff(q, w0, index, rejvec, cvec, lamb));
    return rcpp_result_gen;
END_RCPP
}
// threaddis
double threaddis(double q, double w0, double index, NumericVector rejvec, NumericVector cvec, double sindex, NumericVector kstar, double lamb, double tau);
RcppExport SEXP _SAVA_threaddis(SEXP qSEXP, SEXP w0SEXP, SEXP indexSEXP, SEXP rejvecSEXP, SEXP cvecSEXP, SEXP sindexSEXP, SEXP kstarSEXP, SEXP lambSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< double >::type index(indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rejvec(rejvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cvec(cvecSEXP);
    Rcpp::traits::input_parameter< double >::type sindex(sindexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kstar(kstarSEXP);
    Rcpp::traits::input_parameter< double >::type lamb(lambSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(threaddis(q, w0, index, rejvec, cvec, sindex, kstar, lamb, tau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SAVA_oracsprt", (DL_FUNC) &_SAVA_oracsprt, 4},
    {"_SAVA_falphaplus", (DL_FUNC) &_SAVA_falphaplus, 5},
    {"_SAVA_falphaminus", (DL_FUNC) &_SAVA_falphaminus, 5},
    {"_SAVA_threldpp", (DL_FUNC) &_SAVA_threldpp, 4},
    {"_SAVA_thresaff", (DL_FUNC) &_SAVA_thresaff, 6},
    {"_SAVA_threaddis", (DL_FUNC) &_SAVA_threaddis, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_SAVA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
